<?php
namespace app\modules\broadcast;

/**
 * Created by PhpStorm.
 * User: whts
 * Date: 2020-05-06
 * Time: 11:03
 */
use Yii;
class Module extends \yii\base\Module
{
    /**
     * @inheritdoc
    */
    public $controllerNamespace = "app\modules\broadcast\controllers";

    /**
     * @inheritdoc
    */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->errorHandler->errorAction = 'broadcast/ex/error';
    }
}