version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_db
      MYSQL_USER: news
      MYSQL_PASSWORD: news123
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    platform: linux/amd64
    restart: always
    ports:
      - '6379:6379'

volumes:
  db_data: