version: '3'
services:
  php70fpm:
    build: ./7.0-FPM
    ports:
      - "9002:9000"
    volumes:
      - /data:/data
    links:
      - "mysql56:mysql56con"
      - "redis40:redishost"
    container_name: php70fpm
  mysql56:
    build: ./MySQL/5.6
    ports:
      - "3356:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwe..123
    volumes:
      - /data/database/mysql5.6/data:/var/lib/mysql
      - /data/database/mysql5.6/sock:/var/run/mysqld
    container_name: mysql56
  redis40:
    build: ./Redis/4.0-alpine
    ports:
      - "6300:6379"
    privileged: true
    environment:
      REDIS_PASSWORD: qwe..123
    volumes:
      - /data/database/redis40:/bitnami/redis/data
    container_name: redis40