server {
   charset utf-8;
   client_max_body_size 128M;
   sendfile on;

   listen 80;

   server_name itv.com;
   root        /data/web/itv/web;
   index       index.php index.html;

   location / {
       try_files $uri $uri/ /index.php$is_args$args;
   }

   location /api/ {
       rewrite ^/api/(.*)$ /$1 break;
       proxy_redirect off;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_pass http://fastcgi_php70fpm:9501;
   }

   location ~ ^/(room|mobile)/ {
       proxy_http_version 1.1;
       proxy_redirect off;
       proxy_set_header Host $host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_pass http://fastcgi_php70fpm:9501;
   }

   location ~ \.php$ {
       include fastcgi_params;

       # 这里需要配置成容器内的项目路径， 如果宿主机和 PHP 容器项目不一致的情况下
       # fastcgi_param SCRIPT_FILENAME docker/data/web$fastcgi_script_name;

       fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
       fastcgi_pass   fastcgi_php70fpm:9000;
       try_files $uri =404;
   }
   
   location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
       expires 10d;
       access_log off;
       gzip off;
       try_files $uri =404;
   }

   location ~ /\.(ht|svn|git) {
       deny all;
   }

   location = /favicon.ico {
       log_not_found off;
       access_log off;
   }
}