server {
   charset utf-8;
   client_max_body_size 128M;
   sendfile on;

   listen 80;

   server_name pord.com;
   root        /data/web/pord/web;
   index       index.php index.html;

   location / {
       try_files $uri $uri/ /index.php$is_args$args;
   }

   location ~ \.php$ {
       include        fastcgi_params;
       fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
       fastcgi_pass   127.0.0.1:9001;
       try_files      $uri =404;
   }
   
   location ~ \.(js|css|png|jpg|jpeg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
       expires    10d;
       access_log off;
       gzip       off;
       try_files  $uri =404;
   }

   location ~ /\.(ht|svn|git|scss|es6) {
       deny all;
   }

   location = /favicon.ico {
       log_not_found off;
       access_log    off;
   }
}